arcpy.stats.SpatiallyConstrainedMultivariateClustering(
    in_features="okay_google_open_buildings_sud_haiti_reprojected",
    output_features="okay_buildings_enumeration_areas_v1",
    analysis_fields=["scmc_field"],
    size_constraints="NUM_FEATURES",
    constraint_field=None,
    min_constraint=375,
    max_constraint=750,
    number_of_clusters=None,
    spatial_constraints="TRIMMED_DELAUNAY_TRIANGULATION",
    weights_matrix_file=None,
    number_of_permutations=0,
    output_table="scmc_stats"
)
